### ISSUE TITLE
separate columns

### ISSUE THREAD

**Issue by mockneypiers** [IDDT/wot-console-stats#1]
pulling out the data on excel it'd be nice to have the wn8 values as a plain numeric column, currently it bundles it with the img meaning you have to faff to run comparisons against the old PC value.

Thank you so much for doing this btw, I've been crying out for real console values, especially for unique tanks mapped badly that print wn8 (pz V/IV, sexton 1 etc) that people abuse to stat shame.

**Comment by IDDT** [comment]
Thanks for the feedback! Just added the experimental feature to export data straight into CSV. Use following URL "wot.pythonanywhere.com/export/{type}/{server}/{username}/" where type: (CSV or JSON), server: (xbox or ps4), and username is your Gamertag or PSN. For example, to export my statistics the URL would be "wot.pythonanywhere.com/export/csv/ps4/turboparrot666/". Then in the browser click File > Save As

**Comment by mockneypiers** [comment]
brilliant, you are an absolute superstar.
I am singing your praises on the Beard Guys discord server, though meeting the obvious resistance of people going 'but my {favourite_tank} wn8 is worse'.
Get used to it scrub ;)
